### PR TITLE
upgrade to v2.3 not v2.4, and downgrade v2.4 to v2.3

### PR DESCRIPTION
**Pull request by cubetronic**
this is **COMPLETELY UNTESTED CODE** because i could not get it to build due to dependency problems.

i'm making a lot of assumptions about how things work, like swapping version numbers. my most curious question is.. can i use the "upgrade" function to *downgrade*? also, i just threw in a whole new `miscellaneousChecks2()` function, and i'm assuming i can just do that.

i think making everything downgrade to v2.3 is a good idea. if the user has v2.4 tags and they're working, then they probably won't run this app and so they can keep their v2.4 tags. but if someone needs to *fix* their tags, then we can assume that they really want to make *sure* their tags will work, so changing all v2.4 tags to v2.3 seems like the right thing to do.

### CODE REVIEW

**Comment by Adonai** [comment]
Um, no, you have to add strings and so on for this to work...

> i think making everything downgrade to v2.3 is a good idea

But why? What's wrong with v2.4?

**Comment by cubetronic** [comment]
Vanilla Music Player doesn't handle v2.4 well. From what I gather, it may work on some devices but definitely not all devices. See the Vanilla Music Player FAQ, which recommends v2.3.

**Comment by adrian-bl** [comment]
Vanillas id3v2.4 parsing should be ok these days.

The FAQ was written back then when we used the native parser which failed on 2.4 tags in older android releases

**Comment by Adonai** [comment]
Closing as non-constructive

* Build fails
* Support for outdated standard

**Pull request closed without merging**
